- bitbots_hcm/config/hcm_wolfgang.yaml
- bitbots_hcm/src/bitbots_hcm/hardware_control_manager.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py
Should solve #4 
Programmed by Jasper and me
> HCM: fixed shutting down hcm when waiting for animation server

- bitbots_ik/include/bitbots_ik/BioIKSolver.hpp
- bitbots_ik/src/BioIKSolver.cpp
- bitbots_quintic_walk/CMakeLists.txt
- bitbots_quintic_walk/include/bitbots_quintic_walk/QuinticWalkingNode.hpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/WalkEngine.hpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/common.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/gravity_compensator.h
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/QuinticWalkingNode.cpp
The bio_ik interface has been changed for melodic. The suggested changes contain the removal of the "attempts" parameter in setFromIK, the transition from Eigen Affine3d to Isometry3d and the transition to tf2 that has been made by bio_ik. Compare also the latest commits on bio_ik_service.
I would also suggest to add a tag "kinetic-support" to the commit on the current master (797ba759e06be63f9d7e7d456b1eb43fd624090b).
> New bio ik interface

- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py
Small fix for shutdown procedure when anim server is not running
> HCM: fixed shutdown behavior when anim server is missing

- bitbots_hcm/package.xml
We need the description,  moveit_config  and base footprint for the standalone launch script.
The others should be obvious
> dependencies added

- bitbots_hcm/config/hcm_wolfgang.yaml
The new stand up back animation from Flo should be used.
> use the new stand up back animation

- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
small config changes for presenting push recovery
> small config changes

- bitbots_dynamic_kick/include/bitbots_dynamic_kick/DynamicBalancingGoal.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/KickEngine.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/ReferenceGoals.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/Visualizer.h
- bitbots_dynamic_kick/src/KickEngine.cpp
- bitbots_dynamic_kick/src/Stabilizer.cpp
- bitbots_dynamic_kick/src/Visualizer.cpp
- bitbots_dynup/include/bitbots_dynup/DynamicBalancingGoal.h
- bitbots_dynup/include/bitbots_dynup/DynupEngine.h
- bitbots_dynup/include/bitbots_dynup/ReferenceGoals.h
- bitbots_dynup/package.xml
- bitbots_dynup/src/DynupEngine.cpp
- bitbots_dynup/src/Stabilizer.cpp
- bitbots_ik/CMakeLists.txt
- bitbots_ik/include/bitbots_ik/AnalyticIKSolver.hpp
- bitbots_ik/include/bitbots_ik/BioIKSolver.hpp
- bitbots_ik/package.xml
- bitbots_ik/src/AnalyticIKSolver.cpp
- bitbots_ik/src/BioIKSolver.cpp
- bitbots_quintic_walk/CMakeLists.txt
- bitbots_quintic_walk/include/bitbots_quintic_walk/QuinticWalkingNode.hpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/WalkEngine.hpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/common.h
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/QuinticWalkingNode.cpp
Now after the Walking Refactor in #18 another try of migrating to tf2 as tf is deprecated since ROS Hydro. This has been tested in rviz but not on the real robot yet.
> Upgrade to tf2

- bitbots_animation_server/src/bitbots_animation_server/resource_manager.py
Module level function calls were removed.
> animation_server: make resource manager importable

- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/wait_for.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
this pull request should enable the use of the HCM in simulation
> hcm in simulation

- bitbots_hcm/src/bitbots_hcm/fall_checker.py
Implements the switched signs in the IMU output in the falling detection.
> Switch IMU signs in falling detection

- bitbots_dynamic_kick/launch/test.launch
- bitbots_dynamic_kick/launch/viz.launch
- bitbots_dynup/launch/test.launch
- bitbots_dynup/launch/viz.launch
This pull request adds more launch files to the motion packages for testing and visualization
> Dynup, kick, animation: add launch files for test and visualization

- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
This is necessary for https://github.com/bit-bots/humanoid_league_visualization/pull/4.
> hcm: check if visualization is active before checking IMU

- bitbots_odometry/src/odometry_fuser.cpp
Fix the turned IMU axis in the odom fuser.
> Bitbots_odometry: Fix imu axis

- bitbots_quintic_walk/CMakeLists.txt
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_ik.h
I missed some occurences of `bitbots_ik` in #92.
> walking: remove missed occurences of bitbots_ik

- bitbots_animation_server/launch/test.launch
- bitbots_animation_server/scripts/animation_hcm_bridge.py
adds animation test script and launch
> test animation

- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/visualizer.h
- bitbots_dynamic_kick/src/kick_engine.cpp
- bitbots_dynamic_kick/src/visualizer.cpp
- bitbots_splines/include/bitbots_splines/abstract_engine.h
- bitbots_splines/include/bitbots_splines/abstract_visualizer.h
- bitbots_splines/include/bitbots_splines/position_spline.h
- bitbots_splines/src/Spline/position_spline.cpp
This should be merged after #89 and #90.
> dynamic kick: use new spline types

- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/wait.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
Add a small pause after falling. This closes #96.
> hcm: add pause after falling

- bitbots_animation_server/launch/animation.launch
- bitbots_animation_server/launch/test.launch
- bitbots_animation_server/package.xml
- bitbots_hcm/launch/hcm.launch
- bitbots_hcm/package.xml
- bitbots_quintic_walk/launch/quintic_walk.launch
- bitbots_quintic_walk/launch/quintic_walk_test.launch
- bitbots_quintic_walk/launch/viz.launch
- bitbots_quintic_walk/package.xml
> fix odom + remove respawn

- bitbots_odometry/package.xml
- bitbots_odometry/src/motion_odometry.cpp
- bitbots_odometry/src/odometry_fuser.cpp
just small fix for topic name since it does now include also data from the kick, and not only walking
> odom: fix topic name

- bitbots_dynamic_kick/package.xml
- bitbots_dynamic_kick/scripts/dummy_client.py
- bitbots_dynup/package.xml
- bitbots_dynup/scripts/dummy_client.py
- bitbots_hcm/package.xml
- bitbots_hcm/scripts/MakeGraph.py
- bitbots_hcm/scripts/send_motor_traj.py
- bitbots_hcm/scripts/test_publisher.py
- bitbots_hcm/scripts/test_subscriber.py
- bitbots_hcm/src/bitbots_hcm/hardware_control_manager.py
This pull request updates all shebangs to python3 as we will discuss in our weekly.
> Update shebangs to python3

- bitbots_odometry/include/bitbots_odometry/motion_odometry.h
- bitbots_odometry/include/bitbots_odometry/odometry_fuser.h
- bitbots_odometry/package.xml
I forgot to include the headers in #118, here they are.
> Odometry: add the forgotten headers

- bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg
- bitbots_dynup/cfg/bitbots_dynup_params.cfg
- bitbots_hcm/cfg/hcm_params.cfg
- bitbots_quintic_walk/cfg/bitbots_quintic_walk_engine_params.cfg
- bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg
- bitbots_recordui_rqt/package.xml
change shebang and or package.xml to work with python3
- ~~[ ] Update package version~~
- ~~[ ] Run linters~~
- ~~[ ] Write documentation~~
- ~~[x] Test on your machine~~
> python 3 compatability

- bitbots_splines/include/bitbots_splines/abstract_ik.h
- bitbots_splines/package.xml
> add joint_goals_update_diff method

- bitbots_odometry/package.xml
- bitbots_odometry/src/motion_odometry.cpp
Changes the behaviour of the motion odometry on receiving first support foot information.
https://github.com/bit-bots/bitbots_motion/issues/140
> odom: fix initilization problem

- bitbots_hcm/doc/index.rst
- bitbots_hcm/launch/hcm.launch
- bitbots_hcm/launch/hcm_standalone.launch
- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/stay.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/stop_walking.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
This is a large refactoring of the HCM, which tries to improve the structure from experiences gathered while writing the paper on it. 
Following changes were done:
- HCM now means humanoid control module
- DSD structure is now much more linear and clear
- penalty was renamed to stop (since it is a general stop not only a penalty)
- the robot now stands up again after sitting down
- order of decision classes in decision.py now follows the DSD structure
- some fix for simulation
- animation server is now started when using hcm_standalone.launch
Complete testing in simulation is currently not feasible due to a propblem in the simulation.
> hcm: Refactor

- bitbots_quintic_walk/config/walking_darwin_optimization.yaml
- bitbots_quintic_walk/config/walking_wolfgang_optimization.yaml
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/walk_node.cpp
- bitbots_quintic_walk/src/walk_stabilizer.cpp
Smaller adaptions and fixes for optimization. Also includes fix for wrong odometry in sidewards diretction.
> fix smaller issues for making walking work with optimization

- bitbots_animation_server/launch/test.launch
- bitbots_animation_server/package.xml
- bitbots_animation_server/scripts/animation_hcm_bridge.py
- bitbots_quintic_walk/launch/test.launch
Small fix to make test launch work
> animation: made test launch work

- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
- bitbots_hcm/src/bitbots_hcm/pause.py
- bitbots_quintic_walk/src/walk_node.cpp
https://github.com/bit-bots/humanoid_league_msgs/pull/14
> hcm: refactor speak

- bitbots_odometry/include/bitbots_odometry/motion_odometry.h
- bitbots_odometry/package.xml
- bitbots_odometry/src/motion_odometry.cpp
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/walk_engine.cpp
- bitbots_quintic_walk/src/walk_node.cpp
Fixes an initialization bug of the odometry. For the walk engine odometry as well as for the motion odometry.
> fix odometry bug

- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
Some small fixes for HCM in simulation.
> hcm: small fixes for simulation

- bitbots_animation_server/launch/animation.launch
- bitbots_animation_server/launch/test.launch
- bitbots_animation_server/package.xml
- bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg
- bitbots_dynamic_kick/launch/dynamic_kick.launch
- bitbots_dynamic_kick/launch/test.launch
- bitbots_dynamic_kick/package.xml
- bitbots_dynup/cfg/bitbots_dynup_params.cfg
- bitbots_dynup/launch/dynup.launch
- bitbots_dynup/launch/test.launch
- bitbots_dynup/package.xml
- bitbots_hcm/launch/hcm.launch
- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
- bitbots_odometry/launch/odometry.launch
- bitbots_odometry/package.xml
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
- bitbots_quintic_walk/launch/quintic_walk.launch
- bitbots_quintic_walk/launch/test.launch
- bitbots_quintic_walk/package.xml
Fixes the same issue as https://github.com/bit-bots/bitbots_lowlevel/pull/72
> sets motion nodes to specific cpus

- bitbots_quintic_walk/package.xml
> walk: fix dependency

- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
- bitbots_quintic_walk/package.xml
Fixes some more issues of motion in webots
> changes for webots

- bitbots_hcm/package.xml
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
Tiny fix for simulation. Was broken in last PR
> hcm: fix sim

- bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg
Add very sophisticated and extensively searched params for the kick.
> Make kick work in webots

- bitbots_odometry/src/odometry_fuser.cpp
Same as bit-bots/bitbots_misc#94.
> odometry: fix republishing of transforms in simulation

- bitbots_dynamic_kick/CMakeLists.txt
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_utils.h
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/visualizer.h
- bitbots_dynamic_kick/msg/KickDebug.msg
- bitbots_dynamic_kick/src/kick_engine.cpp
- bitbots_dynamic_kick/src/kick_node.cpp
- bitbots_dynamic_kick/src/visualizer.cpp
This adds debug messages to the dynamic kick to ease debugging.
> Debug msgs for dynamic kick

- bitbots_odometry/src/odometry_fuser.cpp
- bitbots_quintic_walk/config/walking_wolfgang_robot_no_limits.yaml
- bitbots_quintic_walk/launch/quintic_walk_standalone.launch
- bitbots_quintic_walk/launch/test.launch
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/walk_engine.cpp
- bitbots_quintic_walk/src/walk_node.cpp
- bitbots_quintic_walk/src/walk_stabilizer.cpp
Fixes small stupid mistake of not correctly using sim time in simulation. Also fixes some namespace issues. Necessary for https://github.com/bit-bots/parallel_parameter_search/pull/5
> walk: fix sim time issue

- bitbots_dynup/CMakeLists.txt
- bitbots_splines/package.xml
Minor fixes in CMakeLists und package.xml.
> package.xml/CMakeLists.txt misc fixes

- bitbots_hcm/config/hcm_wolfgang.yaml
- bitbots_hcm/src/bitbots_hcm/fall_checker.py
Add time limited queue which stores the classifications. If there any outliers in the queue and the queue contains stable return that we are stable.
Param is not in seconds and not in steps
Closes #200
> Add time based smoothing

- bitbots_quintic_walk/config/walking_wolfgang_robot_no_limits.yaml
Values are taken from `walking_wolfgang_simulator.yaml`.
> Walking: update no_limits config

- bitbots_dynup/README.md
- bitbots_dynup/cfg/bitbots_dynup_params.cfg
- bitbots_dynup/config/dynup_robot.yaml
- bitbots_dynup/config/dynup_sim.yaml
- bitbots_dynup/include/bitbots_dynup/dynup_engine.h
- bitbots_dynup/scripts/dummy_client.py
- bitbots_dynup/src/dynup_engine.cpp
- bitbots_dynup/src/dynup_node.cpp
This resolves some of the remaining issues in the dynup system.
Closes #205 
Closes #214 
Closes #213
> Dynup fixes

- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h
- bitbots_dynamic_kick/src/kick_node.cpp
- bitbots_odometry/CMakeLists.txt
- bitbots_odometry/include/bitbots_odometry/motion_odometry.h
- bitbots_odometry/include/bitbots_odometry/odometry_fuser.h
- bitbots_odometry/src/motion_odometry.cpp
- bitbots_odometry/src/odometry_fuser.cpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h
- bitbots_quintic_walk/src/walk_node.cpp
WIP! Adds some comments describing issues in the motion odometry.
> Fix motion odometry issues

- bitbots_odometry/src/odometry_fuser.cpp
fix https://github.com/bit-bots/bitbots_motion/issues/224
> odom: fix fuser

- bitbots_dynamic_kick/config/kick_config.yaml
Tweaks params a bit, so the robot doesn't fall.
> Tweak kick params for new webots environment

- bitbots_dynamic_kick/config/kick_config.yaml
This changes some params to make the kick stronger.
> kick params for a stronger kick

- Jenkinsfile
- bitbots_animation_server/rosdoc.yaml
- bitbots_hcm/rosdoc.yaml
- bitbots_odometry/.rdmanifest
- bitbots_odometry/package.xml
- bitbots_quintic_walk/rosdoc.yaml
- bitbots_recordui_rqt/rosdoc.yaml
- bitbots_splines/.rdmanifest
- bitbots_splines/rosdoc.yaml
> add odometry and splines `.rdmanifest` files and CI config

- bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg
- bitbots_quintic_walk/config/walking_darwin_optimization.yaml
- bitbots_quintic_walk/config/walking_wolfgang_optimization.yaml
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
- bitbots_quintic_walk/config/walking_wolfgang_robot_no_limits.yaml
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
- bitbots_quintic_walk/config/walking_wolfgang_viz.yaml
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_pywrapper.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_stabilizer.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_utils.h
- bitbots_quintic_walk/launch/test.launch
- bitbots_quintic_walk/src/bitbots_quintic_walk/py_walk_wrapper.py
- bitbots_quintic_walk/src/walk_engine.cpp
- bitbots_quintic_walk/src/walk_node.cpp
- bitbots_quintic_walk/src/walk_pywrapper.cpp
- bitbots_quintic_walk/src/walk_stabilizer.cpp
Manually extracted some improvements from a devel branch.
- some smaller clean up
- introduce parameter to make robot walk really walk with the commanded speed
- improve Python interface
- added namespace 
- special reset that allows to set the walk on any point
- replaced pi with tau
> Walk improvements

- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
fixes https://github.com/bit-bots/bitbots_motion/issues/246
> hcm: change to reporting gettign up

- bitbots_dynup/include/bitbots_dynup/dynup_engine.h
- bitbots_dynup/include/bitbots_dynup/dynup_ik.h
- bitbots_dynup/include/bitbots_dynup/dynup_node.h
- bitbots_dynup/include/bitbots_dynup/dynup_stabilizer.h
- bitbots_dynup/scripts/test_time.py
- bitbots_dynup/src/dynup_engine.cpp
- bitbots_dynup/src/dynup_ik.cpp
- bitbots_dynup/src/dynup_node.cpp
- bitbots_dynup/src/dynup_stabilizer.cpp
- bitbots_dynup/src/visualizer.cpp
Changes code style of Dynup to match ours. No changes in code itself.
> dynup: code style refactor

- bitbots_dynamic_kick/config/kick_config.yaml
> Stop robot from falling during kick

- bitbots_quintic_walk/config/walking_wolfgang_optimization.yaml
- bitbots_quintic_walk/src/walk_pywrapper.cpp
Fix missing parameter in python interface for parallel parameter search
> walk: fix small issues for param optim

- bitbots_dynup/config/dynup_sim.yaml
> change walkready for sim

- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
> small mini param change

- bitbots_dynup/cfg/bitbots_dynup_params.cfg
- bitbots_dynup/config/dynup_optimization.yaml
- bitbots_dynup/config/dynup_robot.yaml
- bitbots_dynup/config/dynup_sim.yaml
- bitbots_dynup/config/dynup_sim_darwin.yaml
- bitbots_dynup/include/bitbots_dynup/dynup_engine.h
- bitbots_dynup/include/bitbots_dynup/dynup_node.h
- bitbots_dynup/src/dynup_engine.cpp
- bitbots_dynup/src/dynup_node.cpp
- bitbots_hcm/config/hcm_wolfgang.yaml
- bitbots_hcm/src/bitbots_hcm/fall_checker.py
> new dynup params

- bitbots_quintic_walk/src/walk_node.cpp
Sometimes we dont get the falling message, so better also listen to getting up
> walk: listen to correct robot state

- bitbots_odometry/src/odometry_fuser.cpp
Catches look up error so that the node does not die
> odom: catch tf lookup

- bitbots_hcm/launch/hcm.launch
Taskset was not correctly used
> Fix taskset usage in hcm

- bitbots_quintic_walk/config/walking_darwin_optimization.yaml
> add missing parameter

- bitbots_dynamic_kick/config/kick_config.yaml
- bitbots_dynamic_kick/config/kick_config_unstable.yaml
- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h
- bitbots_dynamic_kick/launch/dynamic_kick.launch
- bitbots_dynamic_kick/launch/test.launch
- bitbots_dynamic_kick/launch/viz.launch
- bitbots_dynamic_kick/scripts/dummy_client.py
- bitbots_dynamic_kick/src/kick_node.cpp
This adds the configuration for an unstable kick that kicks further and the ability to switch between two configurations to the kick.
Needs bit-bots/bitbots_msgs#23.
> Unstable kick

- bitbots_dynup/cfg/bitbots_dynup_params.cfg
- bitbots_dynup/config/dynup_sim.yaml
- bitbots_dynup/src/dynup_engine.cpp
- bitbots_dynup/src/dynup_node.cpp
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/cancel_goals.py
- bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
- bitbots_quintic_walk/src/walk_node.cpp
> walk: improving params

- bitbots_dynup/src/dynup_ik.cpp
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_utils.h
- bitbots_quintic_walk/src/walk_engine.cpp
- bitbots_quintic_walk/src/walk_node.cpp
Don't let the walk go to a full stop unless you specifically request it. This way we are faster when approaching the ball.
> let walk keep walking

- bitbots_dynup/src/dynup_ik.cpp
> fix broken pr

- bitbots_dynamic_kick/CMakeLists.txt
- bitbots_dynamic_kick/package.xml
- bitbots_dynamic_kick/test/rostests/test_kick_runs.launch
- bitbots_dynamic_kick/test/rostests/test_kick_runs.py
Adds a very simple test for the kick.
> Add simple test if kick is running

- bitbots_dynamic_kick/test/rostests/test_kick_runs.launch
- bitbots_dynamic_kick/test/rostests/test_kick_runs.py
A simple test for the unstable kick.
> Add test for unstable kick

- bitbots_quintic_walk/CMakeLists.txt
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/test/rostests/test_walk_runs.launch
- bitbots_quintic_walk/test/rostests/test_walk_runs.py
> Simple test for walking

- bitbots_odometry/include/bitbots_odometry/motion_odometry.h
- bitbots_odometry/launch/odometry.launch
- bitbots_odometry/src/motion_odometry.cpp
Add scaling factors for improving odometry
> add scaling for odometry

- bitbots_dynamic_kick/scripts/interactive_test.py
Adds an interactive test for the kick.
Code is by @SammyRamone.
> Add interactive test script

- bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h
- bitbots_dynamic_kick/src/kick_node.cpp
- bitbots_dynup/include/bitbots_dynup/dynup_node.h
- bitbots_dynup/src/dynup_node.cpp
- bitbots_odometry/include/bitbots_odometry/motion_odometry.h
- bitbots_odometry/include/bitbots_odometry/odometry_fuser.h
- bitbots_odometry/src/motion_odometry.cpp
- bitbots_odometry/src/odometry_fuser.cpp
- bitbots_quintic_walk/src/walk_node.cpp
> fix sleep issue

- bitbots_animation_server/src/bitbots_animation_server/animation_node.py
- bitbots_hcm/scripts/test_publisher.py
- bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
- bitbots_hcm/src/bitbots_hcm/training/label.py
Introduced in #258.
Remove bitbots_ros_patches as it is not needed anymore.
> Remove bitbots_ros_patches

- bitbots_quintic_walk/config/walking_bez_simulator.yaml
- bitbots_quintic_walk/config/walking_chape_simulator.yaml
- bitbots_quintic_walk/config/walking_mrl_hsl_simulator.yaml
- bitbots_quintic_walk/config/walking_nao_simulator.yaml
- bitbots_quintic_walk/config/walking_nugus_simulator.yaml
- bitbots_quintic_walk/config/walking_op3_simulator.yaml
- bitbots_quintic_walk/config/walking_rfc_simulator.yaml
- bitbots_quintic_walk/config/walking_robotis_op2_simulator.yaml
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
These are the values that the parameter optimization had as a result. Updating the configs accordingly
> optimized values for different robots

- bitbots_quintic_walk/src/walk_node.cpp
> fix typo breaking build

- bitbots_quintic_walk/docs/index.rst
Adds more documentation for the walking
> add walking documentation

- .gitignore
> Ignore rl_walk_models

- bitbots_odometry/src/odometry_fuser.cpp
This workaround is no longer required.
> Remove time hack

- bitbots_dynup/config/dynup_robot.yaml
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
Backwards walking is not so good, every other direction works well. Standup works in both directions. Tested on nuc3/jack.
> Adds more or less working configs for real robot

- bitbots_quintic_walk/src/walk_node.cpp
Without this fix, the walking will create a large CPU load until it first recieves goals. Additionally, it is just unnecessary to compute the IK while the walking is idle.
> walk: reduce load while idle

- bitbots_moveit_bindings/bitbots_moveit_bindings/__init__.py
- bitbots_moveit_bindings/src/bitbots_moveit_bindings.cpp
For https://github.com/bit-bots/bitbots_behavior/pull/260
> bindings: working on fix for head behavior

- bitbots_hcm/src/hcm.cpp
> hcm: fix wrong topic

- bitbots_hcm/config/hcm_wolfgang.yaml
Follow-up on https://github.com/bit-bots/bitbots_lowlevel/pull/104.
> Disable pressure sensors in hcm

- bitbots_hcm/bitbots_hcm/hcm_dsd/decisions/decisions.py
> hcm: fix is walkready

- bitbots_dynamic_kick/src/kick_node.cpp
- bitbots_dynup/src/dynup_node.cpp
- bitbots_hcm/CMakeLists.txt
- bitbots_hcm/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm_blackboard.py
Add handling of overload error
Fix an issue when goals are canceled in dynup and kick
fixes https://github.com/bit-bots/bitbots_lowlevel/issues/46
> add overload handling to hcm; fix cancel issue in kick and dynup

- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/falling_poses.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm_blackboard.py
> hcm: directly execute falling poses

- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/stop_walking.py
- bitbots_hcm/scripts/pause.py
> hcm: fix stop walk on penalty

- bitbots_hcm/launch/hcm.launch
taskset with isolcpu does not easily use multiple cores
> Give only one core to hcm

- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
> walk: tuning parameters

- bitbots_dynup/config/dynup_robot.yaml
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/falling_poses.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
> hcm: replace fallen to side with direct pose

- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/falling_poses.py
To avoid damage and make use of the SEA.
> Move head to the side when we fall to the side

- bitbots_dynup/src/dynup_node.cpp
- bitbots_odometry/src/motion_odometry.cpp
- bitbots_odometry/src/odometry_fuser.cpp
Pass node to transform listener
> Fix TF Node Spam

- bitbots_animation_server/setup.py
- Add empty resource file to add package to ament index
> Fix animation server warnings

- bitbots_quintic_walk/src/walk_engine.cpp
All info in the related issue
https://github.com/bit-bots/bitbots_motion/issues/362
> walk: fix wrong rotation

- bitbots_animation_server/bitbots_animation_server/animation_node.py
- bitbots_animation_server/launch/animation.launch
- bitbots_dynamic_kick/scripts/interactive_test.py
- bitbots_dynamic_kick/src/kick_node.cpp
- bitbots_dynamic_kick/test/rostests/test_kick_runs.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- bitbots_hcm/bitbots_hcm/humanoid_control_module.py
- bitbots_hcm/launch/test.launch
- bitbots_hcm/src/hcm.cpp
- Fix deadlocks in the Animation Stack (HCM + Animation Server)
- Several minor fixes
> Fix animations in the simulator

- bitbots_dynamic_kick/config/kick_sim_config.yaml
- bitbots_dynamic_kick/launch/dynamic_kick.launch
- Load sim parameters
- Set `use_sim_time` parameter in the simulation for the kick
Discovered while testing #373
> Use sim time and sim parameters for kick

- bitbots_dynamic_kick/scripts/interactive_test.py
- bitbots_moveit_bindings/docs/index.rst
> Fix quaternion message

- bitbots_animation_server/bitbots_animation_server/animation_node.py
> fix(animation_server): Fix AttributeError when aborting a goal

- bitbots_dynup/bitbots_dynup_py/py_dynup_wrapper.py
- bitbots_dynup/include/bitbots_dynup/dynup_pywrapper.h
- bitbots_dynup/src/dynup_pywrapper.cpp
- bitbots_moveit_bindings/bitbots_moveit_bindings/__init__.py
- bitbots_moveit_bindings/src/bitbots_moveit_bindings.cpp
- bitbots_moveit_bindings/test/test_moveit_bindings.py
- bitbots_quintic_walk/bitbots_quintic_walk_py/py_walk.py
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_pywrapper.h
- bitbots_quintic_walk/scripts/test_solvable_speeds.py
- bitbots_quintic_walk/src/walk_pywrapper.cpp
Improve the usage of ros2_python_extensions (see PR there)
> Improve usage of ros2_python_extensions

- bitbots_moveit_bindings/bitbots_moveit_bindings/__init__.py
> Add correct return type

- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm_blackboard.py
https://github.com/bit-bots/bitbots_behavior/pull/282#issuecomment-1431563576
> rename topic because of move_base refactor

- bitbots_dynamic_kick/config/kick_sim_config.yaml
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/cancel_goals.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/change_motor_power.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/falling_poses.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/play_animation.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/set_foot_zero.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/stay.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/stop_walking.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/wait.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/actions/wait_for.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- bitbots_hcm/bitbots_hcm/humanoid_control_module.py
- bitbots_hcm/config/hcm_wolfgang.yaml
- bitbots_hcm/src/hcm.cpp
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
- Add consistent typing
- Fix some errors
- Remove unused code
- Fix idle spinning in sim (100% CPU + spam in downstream nodes like the behavior)
- Reduce walking and HCM rates to sim speed
- Fix kick param
> HCM Refactor

- bitbots_quintic_walk/CMakeLists.txt
- bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml
- bitbots_quintic_walk/config/walking_wolfgang_viz.yaml
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h
- bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h
- bitbots_quintic_walk/package.xml
- bitbots_quintic_walk/src/parameters.yaml
- bitbots_quintic_walk/src/walk_engine.cpp
- bitbots_quintic_walk/src/walk_node.cpp
- Use generate_parameter_library for walking
- Cleanup unused variables etc.
> Refactor walking parameters

- bitbots_animation_server/package.xml
- bitbots_dynamic_kick/package.xml
- bitbots_dynup/package.xml
- bitbots_hcm/package.xml
- bitbots_moveit_bindings/package.xml
- bitbots_odometry/package.xml
- bitbots_quintic_walk/package.xml
- bitbots_recordui_rqt/package.xml
- bitbots_rl_motion/package.xml
- bitbots_splines/package.xml
to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html
> fix(package.xml): upgrade to version 3

- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
* Tune the walking after the GORE
> Tune walking params for the Feldraum

- bitbots_dynup/config/dynup_robot.yaml
- bitbots_dynup/include/bitbots_dynup/dynup_engine.h
- bitbots_dynup/src/dynup_engine.cpp
- bitbots_hcm/bitbots_hcm/hcm_dsd/decisions/decisions.py
- bitbots_hcm/config/hcm_wolfgang.yaml
- bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
> Get dynup params from walking

- bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
> Better pose after paused through button

- bitbots_dynup/config/dynup_robot.yaml
- bitbots_dynup/src/dynup_engine.cpp
- Adapt some parameters to walking
- Do not move when waiting in squat position (previously we added different spline points in this position)
> Fix dynup params
