bitbots_quintic_walk/src/QuinticWalk/WalkEngine.cpp
Currently, after the walking has been stopped by sending zero orders, giving orders again leads to a change from 'idle' directly to 'walking' instead of passing through 'startMovement'. This happens because the halfStepFinished property is set to true because the phase and lastPhase are not updated when the state changes from idle to startMovement. This behavior is fixed in this pull request.
=> Walking: fix state confusion after walk stop

bitbots_quintic_walk/src/QuinticWalkingNode.cpp
Currently, the robot model loader (and therefore the bio ik) is initialized twice when the walking starts: Once in the header file where it is declared and a second time in the constructor. This PR moves the initialization to the member initializer list. Thereby, it is only initialized once. 
This kind of double initialization occurs currently quite often, e.g. for the WalkEngine. Those initializations could also be moved to the initializer list, but that is not so crucial as their initialization is not as time consuming.
=> walking: initialize bio ik only once

bitbots_hcm/config/hcm_wolfgang.yaml
@johagge wanted a pull request for this change.
=> use falling animations for falling to right and left instead of walkready

bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg, bitbots_quintic_walk/config/walking_wolfgang_robot.yaml, bitbots_quintic_walk/include/bitbots_quintic_walk/QuinticWalkingNode.hpp, bitbots_quintic_walk/src/QuinticWalkingNode.cpp
tested in visualization, good values still have to be found. since imu is default deactivated currently, I think we can merge this on the master
=> QuinticWalk: added stability criteria for imu angular velocity

bitbots_dynamic_kick/src/KickEngine.cpp
previously the kick-speed was not calculated correctly because of
incorrect quaternion usage. This is now fixed
This should not be merged before testing
=> dynkick: fix speed calculation of spline planning

bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
adds a parameter to chose how many start movements the robot does before starting to walk
=> QuinticWalk: multiple start movements

bitbots_quintic_walk/CMakeLists.txt
removed building unnecessary library for compiling speed up
Improved time for compiling on my laptop from 66s to 36s
=> QuinticWalk: build speed up

bitbots_hcm/src/bitbots_hcm/hardware_control_manager.py
this fixes a bug introduced by https://github.com/bit-bots/bitbots_motion/pull/52
otherwise the joint goals will be played with no effort specified and ros control will not accept the goal messages
=> hcm: fix bug when sending animation without effort

bitbots_dynamic_kick/scripts/dummy_client.py
dynamic kick client does not work when called from external laptop due to time difference issues. there should be at least a warning
better would be to solve the problem completly
=> Fix kick client

bitbots_quintic_walk/include/bitbots_quintic_walk/walk_visualizer.h, bitbots_quintic_walk/src/walk_visualizer.cpp
tf2_eigen has to be included before tf2/LinearMath/... including tf2/convert because else, the template (toMsg) is not defined when the convert template uses it.
=> walking: fix compilation error

bitbots_hcm/src/bitbots_hcm/fall_checker.py
I tested the falling in the simulation and on the robot. By doing so we found a sign error resulting in switched fall direction detections.
=> Falling: Fix sign bug

bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_ik.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/src/kick_ik.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_ik.h, bitbots_quintic_walk/src/walk_ik.cpp
The first commit removes the SEVERE WARNING in the kick that existed because the RobotModelLoader must outlive the loaded RobotModel. The second commit fixes the JointModelGroup pointers in both kick and walking that were shared pointers instead of regular (c style) pointers that are returned by moveit.
=> Fix some memory/pointer problems

bitbots_splines/include/bitbots_splines/position_spline.h, bitbots_splines/src/Spline/position_spline.cpp
Currently, the spline access methods in the PoseSpline are named `x()`, `y()`, etc. while these methods in the PositionSpline are named `getSplineX()`, etc. This pull requests unifies these names.
=> splines: name splines access methods like in pose spline

bitbots_recordui_rqt/src/bitbots_recordui_rqt/record_ui.py
Using the QFileDialogue in this way causes the following warning:
`GtkDialog mapped without a transient parent. This is discouraged.`
This warning does not cause any issues and would need changes to qt itself to get fixed. For reference see: https://github.com/borgbase/vorta/issues/29; https://github.com/FedoraQt/QGnomePlatform/issues/23; https://stackoverflow.com/questions/47847739/qfiledialog-gtkdialog-mapped-without-a-transient-parent
=> recordui: open and save starts at animation directory

bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_node.cpp
this might not fix all crashes but the most obvious ones are now caught.
closes #40
=> dynamic_kick: fix crashes due to invalid tf transformations

bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_utils.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/stabilizer.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/visualizer.h, bitbots_dynamic_kick/package.xml, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/stabilizer.cpp, bitbots_dynamic_kick/src/visualizer.cpp
The DynamicBalancingGoal for BioIK prefers more stable poses but cannot control only a subset of the joints. Therefore, the flying foot is often placed very close to the support leg to be more stable. This results in a bad execution of the kick trajectory. Therefore, the DynamicBalancingGoal is replaced by a PoseGoal for the `base_link`. This is not exactly the center of mass but should be very close to it. Further control happens via the PID controller for the foot pressure sensors.
=> dynamic_kick: directly use trunk pose for stabilizing

bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h, bitbots_dynamic_kick/package.xml, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/stabilizer.cpp
This pull request adds parameters for the trunk orientation (roll, pitch, yaw)
=> kick: add parameters for trunk orientation

bitbots_quintic_walk/include/bitbots_quintic_walk/walk_ik.h, bitbots_quintic_walk/package.xml
This adds a missing `override` in the `walk_ik.h` file that lead to compiler warnings.
=> walking: add missing override in ik header file

bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg, bitbots_dynamic_kick/include/bitbots_dynamic_kick/visualizer.h, bitbots_dynamic_kick/package.xml, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/visualizer.cpp
This pull request enables the debug calculations only when someone subscribes to the corresponding publishers. Therefore, the `force_enable` and `debug_active` parameters are removed.
=> Kick: enable debug when someone subscribes to the publisher

bitbots_odometry/package.xml, bitbots_odometry/src/odometry_fuser.cpp
In case of missing IMU we only want to use the walk odometry
=> odometry: fix to use only walk odometry if IMU is missing

bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_odometry/CMakeLists.txt, bitbots_odometry/launch/odometry.launch, bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp
It is necessary to also include the kick support state into the odometry. This was previously missing.
=> odometry: restructure to include kick support state

bitbots_odometry/CMakeLists.txt, bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp, bitbots_odometry/src/odometry_fuser.cpp
This splits the header files from the source files to make the documentation work. Tested in rViz.
=> Odometry: restructure to include header files

bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_engine.cpp
Add saving of foot state in case of phase reset
https://github.com/bit-bots/bitbots_motion/issues/68
=> walk: add save of foot state for phase reset

bitbots_dynamic_kick/package.xml, bitbots_dynamic_kick/src/visualizer.cpp, bitbots_splines/include/bitbots_splines/abstract_visualizer.h, bitbots_splines/package.xml
This adds a visualization for spline orientations:
=> visualization: add orientation for splines

bitbots_odometry/CMakeLists.txt, bitbots_odometry/include/bitbots_odometry/odometry_fuser.h, bitbots_odometry/package.xml, bitbots_odometry/src/odometry_fuser.cpp
This pull request mostly removes the usage of Euler coordinates from the odometry fuser.
This also implements the rot_conv library for this task.
Use quaternions for yaw removal with the rot_conv library.
#129
=> Fix: Odometry fuser Z axis

bitbots_splines/include/bitbots_splines/abstract_ik.h
This pull request makes `joint_goals_update` and `joint_goals_update_diff` inline. This is necessary if we want to keep most of the splines library header-only because otherwise, the function is defined multiple times. It would probably make sense to move this to a separate cpp file, as well as the visualizer methods.
#134, #135
=> splines: make joint_goals_update and joint_goals_update_diff inline

bitbots_quintic_walk/cfg/bitbots_quintic_walk_engine_params.cfg, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_engine.cpp
Introduces an experimental parameter for adding trunk movement in z direction. This could maybe lessen stress on support leg as it does not have to turn as much.
This is still highly experimental and therefore only a draft.
=> walk: introduce trunk movement in z direction

bitbots_recordui_rqt/package.xml, bitbots_recordui_rqt/src/bitbots_recordui_rqt/animation_recording.py, bitbots_recordui_rqt/src/bitbots_recordui_rqt/record_ui.py
Changes iteritems() to items() and valueChanged signal to sliderMoved signal.
Fixes issue #139
=> Adapt recordui to python3 syntax changes

bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml, bitbots_quintic_walk/launch/test.launch, bitbots_quintic_walk/package.xml
Makes the test launch of quintic walk usable in for simulation and gives it a better name .
=> walk: adapt test launch for simulator and rename

bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg, bitbots_quintic_walk/config/walking_wolfgang_robot.yaml, bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml, bitbots_quintic_walk/config/walking_wolfgang_viz.yaml, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_ik.h, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_ik.cpp, bitbots_quintic_walk/src/walk_node.cpp
Adds a new option to use the joint effort information to check if the flying leg made ground contact (instead of pressure sensor).
Can be used on robots without pressure sensors, or as a fallback if foot sensors fail.
=> Walk: Phase resetting via joint effort

bitbots_dynamic_kick/launch/dynamic_kick.launch, bitbots_dynamic_kick/package.xml, bitbots_dynup/launch/dynup.launch, bitbots_dynup/package.xml
Since https://github.com/bit-bots/bitbots_misc/pull/63, a launch file for dynup is referenced in `motion.launch`. This launch file exists only on branch `feature/dynup-ba`. This PR adds a simple launch file for dynup and dynamic kick to make switching branches in the repo easier.
=> add launch files for dynup and kick

bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_engine.cpp, bitbots_quintic_walk/src/walk_node.cpp
This adds a new stability option called "phase rest" that lets the walking rest at an end of a step until a phase reset occurs. This helps in situation where the robot is tilting to the side and the flying foot did not make ground contact during the step.
=> walk: phase rest

bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp, bitbots_quintic_walk/cfg/bitbots_quintic_walk_params.cfg, bitbots_quintic_walk/config/walking_wolfgang_robot.yaml, bitbots_quintic_walk/config/walking_wolfgang_robot_slow_steps.yaml, bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml, bitbots_quintic_walk/config/walking_wolfgang_viz.yaml, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_engine.h, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_utils.h, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_engine.cpp, bitbots_quintic_walk/src/walk_node.cpp
This PR adds the ability to walk upwards and downwards by setting the linear z component of the command velocities. It will be merged on the `running_robot_competition` branch.
=> Add upwards/downwards walking

bitbots_animation_server/package.xml, bitbots_animation_server/src/bitbots_animation_server/animation_node.py
`animator` can be None when the animation does not exist, that must be checked for and the execution of the animation must be aborted.
=> Catch execution of unexisting animations correctly

bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp, bitbots_odometry/src/odometry_fuser.cpp
Small fix against spam of warnings when robot is started
=> odom: reduce warnings

bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp
This PR removes the z movement from the odometry which was introduced in #158 and resulted in a drift in the z axis. It closes #162.
=> Remove z movement from odometry

bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/wait.py
The HCM dies after falling in the simulation:
```
Traceback (most recent call last):
File "/home/florian/catkin/src/bitbots_meta/bitbots_motion/bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py", line 272, in <module>
hcm = HardwareControlManager()
File "/home/florian/catkin/src/bitbots_meta/bitbots_motion/bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py", line 81, in __init__
self.main_loop()
File "/home/florian/catkin/src/bitbots_meta/bitbots_motion/bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py", line 239, in main_loop
self.dsd.update()
File "/home/florian/catkin/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider/src/dynamic_stack_decider/dsd.py", line 203, in update
result = current_instance.perform()
File …
```
=> Fix dsd field name

bitbots_hcm/package.xml, bitbots_hcm/src/bitbots_hcm/fall_checker.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/wait.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py
- Dont interpret quaternion as euler angles in the `falling`
- Use fused angles instead of euler
- Use orientation instead of gyro to determine the `falling` direction if a fall is detected (less issues with bouncing robots)
- Use fused angles to determine the `fallen` detection
- Remove `hacky_sequence_dynup_running` which blocks falling very oftern in sim (maybe also on robot)
=> Fix falling and fallen

bitbots_hcm/package.xml, bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
This adds a simple check to the `Sitting` decision so that the hcm does not die when `current_joint_state` is not set yet. This can only happen in visualization when the motor helper script is loaded after the hcm. A similar check already exists in the `is_walkready` method.
=> hcm: fix NoneType problem when joint states are not set on startup

bitbots_hcm/package.xml, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/stay.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
This removes the last element of the hcm decision tree where walkready is always executed. At startup and after turning the motors back on, walkready is still executed.
=> hcm: do not play walkready animation on idle

bitbots_dynamic_kick/launch/test.launch
This adds a `sim` parameter to the `test.launch` launch file of the dynamic kick.
=> kick: add sim parameter to launch file

bitbots_dynamic_kick/config/kick_config.yaml
This pull requests improves the velocity of the kick from almost five seconds to 1.5 seconds. It is stable in webots, when testing please keep in mind to set the robot to walkready before executing the kick.
=> Improve kick time

bitbots_hcm/config/hcm_wolfgang.yaml, bitbots_hcm/src/bitbots_hcm/fall_checker.py
Fixes the missing smoothing threshold in the FallChecker. It was previously only used when the FallChecker was used through the classifier class.
The threshold prevents invoking fall measurements after a false positive due to message outliers.
=> hcm: fix smoothing in fall checker

bitbots_dynamic_kick/CMakeLists.txt, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_ik.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_pywrapper.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_utils.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/visualizer.h, bitbots_dynamic_kick/msg/KickDebug.msg, bitbots_dynamic_kick/scripts/dummy_client.py, bitbots_dynamic_kick/setup.py, bitbots_dynamic_kick/src/bitbots_dynamic_kick/__init__.py, bitbots_dynamic_kick/src/bitbots_dynamic_kick/py_kick_wrapper.py, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_ik.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/kick_pywrapper.cpp, bitbots_dynamic_kick/src/stabilizer.cpp, bitbots_dynamic_kick/src/visualizer.cpp
Similar to the existing one for the walking, this PR adds a python wrapper to the kick. Additionally, the code was refactored to use the Eigen geometry library and rot_conv for rotation conversions. This significantly cleans up the code.
=> Add a python wrapper for the kick

bitbots_dynamic_kick/CMakeLists.txt, bitbots_dynamic_kick/config/kick_config.yaml, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_pywrapper.h, bitbots_dynamic_kick/scripts/dummy_client.py, bitbots_dynamic_kick/src/bitbots_dynamic_kick/py_kick_wrapper.py, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/kick_pywrapper.cpp
This adds some fixes used for the kick parameter optimization:
- remove the rest of tf and instead calculate base_footprint ourselves by just using the mean y value of both feet (what do you think, is that a valid assumption?)
- improve the usage of foot distance parameter (it is now the foot distance during the kick only, the robot returns to its initial position after the kick)
- remove bio_ik from cmakelists (see TAMS-Group/bio_ik#29)
- add a first set of learned parameters
=> Fixes for kick parameter optimization

bitbots_dynamic_kick/src/kick_node.cpp
Previously, we only checked if `percent_done == 100`. However, in simulation, the timesteps can be large enough to skip directly from `99` to `100`. In that case, the kick just continued to run until `percent_done` overflowed (it is only a `uint8`, so that happened quite fast`) and went back to zero and so on.
=> Fix termination of kick

bitbots_dynamic_kick/config/kick_config.yaml, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_engine.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_pywrapper.h, bitbots_dynamic_kick/package.xml, bitbots_dynamic_kick/src/bitbots_dynamic_kick/py_kick_wrapper.py, bitbots_dynamic_kick/src/kick_engine.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/kick_pywrapper.cpp
This pull request adds the function `getTrunkPose()` to the python interface of the kick. The function returns the current pose of the trunk relative to the support foot.
In addition, the rotation parameters have been changed from the `deg()` notation to the actual value in radians. While the `deg` notation is a nice addition to YAML, it is only implemented in the roslaunch yaml parser. When the parameter file is loaded manually, for example for parameter loading, it does not work.
=> Additions to kick python interface

bitbots_dynup/cfg/bitbots_dynup_params.cfg, bitbots_dynup/config/dynup_robot.yaml, bitbots_dynup/config/dynup_sim.yaml, bitbots_dynup/config/dynup_sim_darwin.yaml, bitbots_dynup/include/bitbots_dynup/dynup_node.h, bitbots_dynup/include/bitbots_dynup/dynup_stabilizer.h, bitbots_dynup/src/dynup_engine.cpp, bitbots_dynup/src/dynup_node.cpp, bitbots_dynup/src/dynup_stabilizer.cpp
This pull request adds two new parameters. After a dynup request is completed, if stabilizing is enabled, the PD controller will keep regulating the motion until the robots absolute fused error is below `stable_threshold` for `stable_duration` cycles.
Closes #230 
- ~[ ] Update package version~
=> Dynup now keeps stabilizing until robot is stable after completed motion

bitbots_dynup/config/dynup_robot.yaml
The space between the colon and the number is missing, making the yaml invalid.
Introduced in 56fb7b6e7c957c9fed3731d57b46907eef3cdf7a in #222.
=> Fix invalid yaml in dynup config

bitbots_odometry/CMakeLists.txt, bitbots_odometry/include/bitbots_odometry/odometry_fuser.h, bitbots_odometry/package.xml, bitbots_odometry/src/odometry_fuser.cpp
* Refactor the odometry fuser
* Use `message_filters` to sync the messages before fusing them.
=> Refactor the odometry fuser

bitbots_dynup/cfg/bitbots_dynup_params.cfg, bitbots_dynup/config/dynup_robot.yaml, bitbots_dynup/config/dynup_sim.yaml, bitbots_dynup/src/dynup_engine.cpp
* Changes Dynup param to create a new walkready pose.
* This is done to reduce the visibility of th arms in the camera image.
* 
bit-bots/wolfgang_robot#125
=> Change the walkready pose in dynup

bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_node.h, bitbots_dynamic_kick/include/bitbots_dynamic_kick/kick_pywrapper.h, bitbots_dynamic_kick/src/bitbots_dynamic_kick/py_kick_wrapper.py, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynamic_kick/src/kick_pywrapper.cpp
This adds a method `is_left_kick()` to the python interface. It is needed for the reinforcement-learned kick.
=> kick: add is_left_kick method to python interface

bitbots_animation_server/config/animation.yaml, bitbots_animation_server/launch/animation.launch, bitbots_animation_server/scripts/animation_hcm_bridge.py, bitbots_animation_server/scripts/run_animation.py, bitbots_animation_server/src/bitbots_animation_server/animation.py, bitbots_animation_server/src/bitbots_animation_server/animation_node.py, bitbots_animation_server/src/bitbots_animation_server/resource_manager.py, bitbots_animation_server/src/bitbots_animation_server/spline_animator.py
This PR includes two changes:
1. Add a cache to animations so that the json files are not read every time again
2. Fix torque reading, currently the torque value of the last keyframe is used for all keyframes
This touches #208, but reads the animation when it is used for the first time because we have no way of knowing which animations will be used. Should we just load all animations? Or specify a list in the config file?
=> Add animation cache and fix torque in animations

bitbots_dynamic_kick/package.xml, bitbots_dynup/package.xml, bitbots_quintic_walk/package.xml
This adds the `control_toolbox` dependency to the package.xml files.
=> Add missing dependencies

bitbots_dynup/config/dynup_robot.yaml
This just copies the parameters from dynup_sim.yaml to dynup_robot.yaml because the current parameters don't match the update walkready.json. This results in the hcm being stuck in the startup phase because the desired walkready position is never reached. (By the way, could the check and comparison to the json file be replaced by a correct handling of the action results returned by the dynup?)
These parameters are probably not working on the real robot, so maybe a more sophisticated method of merging the configs would be better.
The walkready animation was updated in bit-bots/wolfgang_robot#125, the dynup_sim parameters were updated in #239.
=> Update dynup_robot params from dynup_sim

bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/cancel_goals.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/change_motor_power.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/stay.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/stop_walking.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm_blackboard.py, bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
Currently, the robot states from humanoid_league_msgs/RobotControlState are redefined in the HCM. This might lead to problems when the message is changed. With this PR, the HCM uses the definitions from the message directly.
=> HCM: Fix duplicate definition of robot states

bitbots_animation_server/src/bitbots_animation_server/animation_node.py, bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
This deactivates the shutdown hook that lets the robot sit down in the animation server and the hcm when the simulation is active. In simulation, this feature is not needed because no harm to the motors is done on shutdown. Deactivating it leads to a significantly more pleasant debugging experience, because you don't have to wait after pressing Ctrl-C.
=> Deactivate shutdown hook for sitdown in simulation

bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
Optimizes HCM for https://github.com/bit-bots/bitbots_motion/issues/248
Removes waits which are unnecessary in simulation and maybe also in real robot by now (since Dynup can handle better some movement in the beginning)
=> remove waits in HCM

bitbots_dynup/include/bitbots_dynup/dynup_engine.h, bitbots_dynup/include/bitbots_dynup/dynup_utils.h, bitbots_dynup/src/dynup_engine.cpp, bitbots_dynup/src/dynup_ik.cpp, bitbots_dynup/src/dynup_stabilizer.cpp
Fixes https://github.com/bit-bots/bitbots_motion/issues/250
Also changes the head position during stand up to be more extreme. I think this will help pushing the CoM a bit more into the right direction.
https://user-images.githubusercontent.com/11520148/119804865-0b36ec80-bee1-11eb-8751-ff20c176ddd3.mp4
=> dynup: make head go to zero

bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
The robot state was set to `GETTING_UP` when dynup is used to set the position to walkready. This is wrong and confuses the localization. Instead, the state should not be set in this case and remain `STARTUP`.
=> Fix GETTING_UP state in initial state

bitbots_quintic_walk/src/walk_node.cpp
This removes a workaround that was added in eab861f8de10cdbc6b6e3a30f358dd3c8fbfaf91 (#143) and results in the error `Tried to advertise a service that is already advertised in this node [/walking/engine/set_parameters]` when launching the walking. @SammyRamone do you know why the workaround was necessary? It seems to be related to the PID controllers. Could you test whatever it was that this line fixed? The walking still seems to work without the line.
=> Remove double initialization of walk engine

bitbots_dynamic_kick/CMakeLists.txt, bitbots_dynamic_kick/src/kick_ik.cpp, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynup/CMakeLists.txt, bitbots_dynup/src/dynup_ik.cpp, bitbots_dynup/src/dynup_node.cpp, bitbots_dynup/src/dynup_stabilizer.cpp, bitbots_moveit_bindings/CMakeLists.txt, bitbots_moveit_bindings/src/bitbots_moveit_bindings.cpp, bitbots_odometry/CMakeLists.txt, bitbots_odometry/src/motion_odometry.cpp, bitbots_odometry/src/odometry_fuser.cpp, bitbots_quintic_walk/CMakeLists.txt, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_ik.h, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_stabilizer.h, bitbots_quintic_walk/src/walk_engine.cpp, bitbots_quintic_walk/src/walk_ik.cpp, bitbots_quintic_walk/src/walk_node.cpp, bitbots_quintic_walk/src/walk_pywrapper.cpp, bitbots_quintic_walk/src/walk_visualizer.cpp, bitbots_splines/CMakeLists.txt, bitbots_splines/include/bitbots_splines/abstract_ik.h, bitbots_splines/include/bitbots_splines/reference_goals.h
Yesterday, I spent quite some time debugging a problem in the particle filter that would have been found easily with `-Wall` (bit-bots/particle_filter#7). A similar problem happened a few months ago (bit-bots/particle_filter#5).
This PR adds the compile flags `-Wall -Werror -Wno-unused` to the motion packages. `-Wall` shows all warnings. `-Werror` treats all warnings as errors, failing the build. I added that one because warnings tend to be ignored by most people. `-Wno-unused` turns off warnings for unused functions or variables which would be annoying when writing new code or debugging things.
This will hopefully lead to less problems that would have been so easily avoidable in the future.
=> Use -Wall in motion cpp packages

bitbots_dynup/config/dynup_robot.yaml, bitbots_dynup/config/dynup_sim.yaml, bitbots_dynup/config/dynup_sim_darwin.yaml, bitbots_quintic_walk/config/walking_wolfgang_robot.yaml, bitbots_quintic_walk/config/walking_wolfgang_robot_no_limits.yaml, bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml, bitbots_quintic_walk/config/walking_wolfgang_viz.yaml
Just deactivate publishing of PID controller states as default. Can be reactivated in dyn reconf anyway if necessary. Reduces CPU load and bandwith.
=> deactivate unnecessary publishing of pid states

bitbots_animation_server/src/bitbots_animation_server/animation_node.py, bitbots_dynamic_kick/src/kick_node.cpp, bitbots_dynup/src/dynup_node.cpp, bitbots_hcm/scripts/test_publisher.py, bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py, bitbots_hcm/src/bitbots_hcm/training/label.py, bitbots_odometry/src/motion_odometry.cpp, bitbots_odometry/src/odometry_fuser.cpp, bitbots_quintic_walk/config/walking_wolfgang_simulator.yaml, bitbots_quintic_walk/src/walk_node.cpp
The rospy and roscpp implementation of rate.sleep() does not work correctly when the specified rate is higher than the simulation rate. We need to handle this explicitly.
Python uses wrapper, c++ not. We will probably do this differently with ROS2 anyway.
=> Rate.sleep issues in sim

bitbots_dynamic_kick/config/kick_config.yaml
New kick parameters from the optimization with MOTPE in the current webots environment.
This is the evaluation:
=> New kick params from optimization

bitbots_dynup/cfg/bitbots_dynup_params.cfg, bitbots_dynup/config/dynup_robot.yaml, bitbots_dynup/config/dynup_sim.yaml, bitbots_dynup/config/dynup_sim_darwin.yaml, bitbots_dynup/src/dynup_engine.cpp, bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/hcm.dsd
The simulation sends an empty joint state message at start which confused us. Furthermore we always used dynup rise to go into walkready, but this can be quiet fast. Now we can do this slower
=> fixes initial walkready

bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py, bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
* Enable walkready during `CONTROLLABLE`
* Fix finished
This should fix the that the robot falls down after the penalty.
=> Fix walkready animation call from behavior

bitbots_animation_server/src/bitbots_animation_server/animation_node.py
Some warnings of the animation server are crucial and should not be ignored. Therefore they are changed to errors.
=> Change some warnings of the animation server to errors

bitbots_hcm/src/bitbots_hcm/fall_checker.py, bitbots_hcm/src/bitbots_hcm/hcm_dsd/actions/play_animation.py
Currently, the default values for the fall checker are loaded as default values for keyword arguments. The problem is that these default values are accessed at import time. This can lead to undesired side effects when the fall checker or something that imports it, like the blackboard, is imported when the hcm parameters are not loaded.
=> Fix access to ros parameters at import time

bitbots_dynamic_kick/CMakeLists.txt
bitbots_test has to be at the bottom because the catkin libraries etc are overwritten by the second find_package.
Needed because of #288.
=> Move bitbots_tests to the bottom

bitbots_dynup/CMakeLists.txt, bitbots_dynup/package.xml, bitbots_dynup/test/rostests/test_dynup_runs.launch, bitbots_dynup/test/rostests/test_dynup_runs.py
Basically the same as #288.
Tests for all directions if they do anything. Would have prevented #287 and the abortion of our test game today.
=> Add simple test for dynup

bitbots_dynamic_kick/src/kick_node.cpp
Fixes dynamic reconfigure for the kick (regression in #281).
=> Fix for dynamic reconfigure

bitbots_hcm/src/bitbots_hcm/hcm_dsd/decisions/decisions.py
Parameter was hard coded instead using the one from config
=> hcm: not usesd parameter

bitbots_dynamic_kick/CMakeLists.txt, bitbots_dynamic_kick/package.xml, bitbots_dynup/CMakeLists.txt, bitbots_dynup/package.xml, bitbots_odometry/CMakeLists.txt, bitbots_odometry/package.xml, bitbots_quintic_walk/CMakeLists.txt, bitbots_quintic_walk/package.xml
The dependency `rotconv` was renamed to `rot_conv`
bit-bots/rot_conv_lib/pull/5
ros-sports/humanoid_base_footprint/pull/37
=> Fix rot_conv dep

bitbots_odometry/src/motion_odometry.cpp
Small fix for odom z value that was wrongly set to 0 in https://github.com/bit-bots/bitbots_motion/pull/325
=> odom: fix z value of odom

bitbots_quintic_walk/config/walking_wolfgang_robot.yaml
This disables the PID controllers in the walking for now because they are unstable. Smaller values can probably be added back later when the final parameters are done.
=> Disable walk pid controllers

bitbots_hcm/CMakeLists.txt
Adds [required](https://pybind11.readthedocs.io/en/stable/faq.html#someclass-declared-with-greater-visibility-than-the-type-of-its-field-someclass-member-wattributes) compiler flag, which also fixes build warning.
=> Fix hcm build warning

bitbots_dynamic_kick/src/kick_node.cpp
```
/colcon_ws/src/bitbots_meta/bitbots_motion/bitbots_dynamic_kick/src/kick_node.cpp: In constructor ‘bitbots_dynamic_kick::KickNode::KickNode(const string&, std::vector<rclcpp::Parameter>)’:
/colcon_ws/src/bitbots_meta/bitbots_motion/bitbots_dynamic_kick/src/kick_node.cpp:51:21: error: ‘use_center_of_pressure’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
51 |   stabilizer_.useCop(use_center_of_pressure);
|   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/KickNode.dir/build.make:76: CMakeFiles/KickNode.dir/src/kick_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:594: CMakeFiles/KickNode.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
=> Fix uninitialized value

bitbots_hcm/bitbots_hcm/hcm_dsd/actions/falling_poses.py
This unused import requires `tkinter` and I don't even understand why it is there...
=> Removed unused import

bitbots_moveit_bindings/CMakeLists.txt, bitbots_moveit_bindings/bitbots_moveit_bindings/__init__.py, bitbots_moveit_bindings/package.xml, bitbots_moveit_bindings/src/bitbots_moveit_bindings.cpp
This PR fixes the usage of bitbots_moveit_bindings with the bio_ik as it is used for `LookAt` in the behavior.
=> Fix bio ik usage in moveit bindings

bitbots_hcm/bitbots_hcm/humanoid_control_module.py
- Write it in caps so it is pronounced "H C M" otherwise it is skipped by the new tts.
=> Fix the word "HCM" in the TTS

bitbots_hcm/bitbots_hcm/hcm_dsd/decisions/decisions.py, bitbots_hcm/bitbots_hcm/hcm_dsd/hcm.dsd
robot did only rarely go into walkready on startup, works consistently now
=> check for initial ourselves instead of using reevaluate

bitbots_dynup/CMakeLists.txt, bitbots_dynup/include/bitbots_dynup/dynup_node.h, bitbots_dynup/package.xml, bitbots_dynup/src/dynup_node.cpp, bitbots_hcm/CMakeLists.txt, bitbots_hcm/package.xml, bitbots_hcm/src/hcm.cpp, bitbots_moveit_bindings/CMakeLists.txt, bitbots_moveit_bindings/package.xml, bitbots_moveit_bindings/src/bitbots_moveit_bindings.cpp, bitbots_odometry/CMakeLists.txt, bitbots_odometry/include/bitbots_odometry/motion_odometry.h, bitbots_odometry/include/bitbots_odometry/odometry_fuser.h, bitbots_odometry/package.xml, bitbots_odometry/src/motion_odometry.cpp, bitbots_odometry/src/odometry_fuser.cpp, bitbots_quintic_walk/CMakeLists.txt, bitbots_quintic_walk/include/bitbots_quintic_walk/walk_node.h, bitbots_quintic_walk/package.xml, bitbots_quintic_walk/src/walk_node.cpp
- Use released events executor binaries from rclcpp
PR because https://github.com/ros2/rclcpp/pull/2155 is merged and released.
=> Use rclcpp events executor
